//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k1stroy.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public int OrderCreatorID { get; set; }
        public int OrderProductID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderCompleteDate { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public string ContactData { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> StorageFrom { get; set; }
        public string StorageTo { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Status Status { get; set; }
        public virtual Storages Storages { get; set; }
        public virtual Users Users { get; set; }
    }
}
